export enum ActionTypeCart {
  CART_ADD_ITEM = "CART_ADD_ITEM",
  CART_REMOVE_ITEM = "CART_REMOVE_ITEM",
  CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS",
  CART_SAVE_PAYEMENT_METHOD = "CART_SAVE_PAYEMENT_METHOD",
  CART_EMPTY = "CART_EMPTY",
  CART_ADD_CARTID = "CART_ADD_CARTID",
}
