export enum ActionTypeOrder {
  ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL",
  ORDER_CREATE_RESET = "ORDER_CREATE_RESET",

  ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAIL = "ORDER_PAY_FAIL",
  ORDER_PAY_RESET = "ORDER_PAY_RESET",

  ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL",

  ORDER_MINE_LIST_REQUEST = "ORDER_MINE_LIST_REQUEST",
  ORDER_MINE_LIST_SUCCESS = "ORDER_MINE_LIST_SUCCESS",
  ORDER_MINE_LIST_FAIL = "ORDER_MINE_LIST_FAIL",

  ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST",
  ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS",
  ORDER_LIST_FAIL = "ORDER_LIST_FAIL",

  ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST",
  ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS",
  ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL",
  ORDER_DELETE_RESET = "ORDER_DELETE_RESET",

  ORDER_SUMMARY_REQUEST = "ORDER_SUMMARY_REQUEST",
  ORDER_SUMMARY_SUCCESS = "ORDER_SUMMARY_SUCCESS",
  ORDER_SUMMARY_FAIL = "ORDER_SUMMARY_FAIL",
}
