export enum ActionTypeUser {
  USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST",
  USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL",

  USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL",
  CURRENT_USER = "CURRENT_USER",

  USER_SIGNOUT = "USER_SIGNOUT",
}
